---
services:
  fossflow:
    image: stnsmith/fossflow:latest
    container_name: "fossflow-${HOSTNAME}" #
    hostname: "fossflow-${HOSTNAME}" #
    env_file:
      - "${BAK_CFG_DIR}/fossflow/.env"
    restart: unless-stopped
    volumes:
      - "${BAK_CFG_DIR}/fossflow:/data/diagrams"
    ports:
      - 9632:80
    networks:
      - proxy
    labels:
      traefik.enable: true
      traefik.http.routers.fossflow.middlewares: oauth@file #add this to any container you want to use the Authentik web proxy
      traefik.http.routers.fossflow.rule: Host(`fossflow.${CF_DOMAIN}`)

networks:
  proxy:
    external: true
